"use client";

import { useState, useEffect } from "react";
import { getApiBaseUrl } from "@/lib/api";
import SafeMarkdown from "@/lib/markdown";

export default function VeraReport() {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [expandedSections, setExpandedSections] = useState({});
  const [checkedItems, setCheckedItems] = useState({});
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const baseUrl = getApiBaseUrl();
        const user = localStorage.getItem("liverisk_user_id") || localStorage.getItem("liverisk_user") || "0";
        const token = localStorage.getItem("liverisk_token");

        const res = await fetch(`${baseUrl}/agent/report`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
          },
          body: JSON.stringify({ user_id: user }),
        });
        const data = await res.json();
        if (!cancelled) setReport(data);
      } catch (error) {
        console.error("Report generation error:", error);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const toggleSection = (idx) => {
    setExpandedSections((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const handleDownloadPdf = async () => {
    if (report?.report_markdown) {
      const blob = new Blob([report.report_markdown], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `LiveRisk_Report_${new Date().toISOString().slice(0, 10)}.md`;
      a.click();
      URL.revokeObjectURL(url);
      return;
    }
    const baseUrl = getApiBaseUrl();
    const user = localStorage.getItem("liverisk_user_id") || localStorage.getItem("liverisk_user") || "0";
    const token = localStorage.getItem("liverisk_token");
    try {
      const res = await fetch(`${baseUrl}/agent/report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ user_id: user }),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.report_markdown) {
          const blob = new Blob([data.report_markdown], { type: "text/markdown" });
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `LiveRisk_Report_${new Date().toISOString().slice(0, 10)}.md`;
          a.click();
          URL.revokeObjectURL(url);
        }
      }
    } catch (e) {
      console.error("Download error:", e);
    }
  };

  const handleShare = () => {
    const url = window.location.href;
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (loading) {
    return (
      <div style={{ textAlign: "center", padding: 60, color: "#71717a" }}>
        <div className="loader-ring" style={{ margin: "0 auto 16px" }} />
        <p>Generating institutional report...</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div style={{ textAlign: "center", padding: 60, color: "#71717a" }}>
        <p>Click generate to create a portfolio risk report</p>
        <button onClick={generateReport}>Generate Report</button>
      </div>
    );
  }

  const sections = (report.report_markdown || "")
    .replace(/^# /gm, "## ")  // normalize h1 to h2 for consistent splitting
    .split("## ").filter(Boolean);
  const forecast = report.forecast || {};
  const actionItems = report.action_items || [];

  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: "0 16px" }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 16,
        }}
      >
        <div>
          <h2 style={{ margin: 0, fontSize: 18, fontWeight: 700, color: "#e4e4e7" }}>
            Portfolio Intelligence Report
          </h2>
          <p style={{ margin: 0, fontSize: 11, color: "#71717a" }}>
            Generated by Vera AI · Health: {report.health_score}/100
          </p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button
            onClick={handleDownloadPdf}
            style={{
              background: "#00e676",
              color: "#000",
              fontWeight: 600,
              padding: "8px 16px",
              borderRadius: 8,
              border: "none",
              cursor: "pointer",
              fontSize: 12,
            }}
          >
            Download PDF
          </button>
          <button
            onClick={handleShare}
            style={{
              background: "transparent",
              color: copied ? "#00e676" : "#3b82f6",
              border: "1px solid #27272a",
              padding: "8px 16px",
              borderRadius: 8,
              cursor: "pointer",
              fontSize: 12,
            }}
          >
            {copied ? "Copied!" : "Share"}
          </button>
        </div>
      </div>

      {/* Scenario Cards */}
      {forecast.bull && forecast.base && forecast.bear && (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(3, 1fr)",
            gap: 12,
            marginBottom: 20,
          }}
        >
          {[
            { key: "bull", label: "Bull Case", color: "#00e676" },
            { key: "base", label: "Base Case", color: "#f59e0b" },
            { key: "bear", label: "Bear Case", color: "#ef4444" },
          ].map(({ key, label, color }) => {
            const s = forecast[key];
            return (
              <div
                key={key}
                style={{
                  background: "#14141a",
                  border: `1px solid ${color}30`,
                  borderRadius: 12,
                  padding: 16,
                }}
              >
                <h4 style={{ color, margin: "0 0 8px", fontSize: 13, fontWeight: 600 }}>
                  {label}
                </h4>
                <div style={{ fontSize: 24, fontWeight: 700, color: "#e4e4e7" }}>
                  {s.probability}%
                </div>
                <div style={{ fontSize: 14, color: "#a1a1aa", margin: "4px 0" }}>
                  {s.return_pct > 0 ? "+" : ""}{s.return_pct}% return
                </div>
                <p style={{ fontSize: 11, color: "#71717a", margin: "8px 0" }}>
                  {s.trigger}
                </p>
                <p style={{ fontSize: 11, color, margin: 0 }}>
                  {s.action}
                </p>
                {key === "bear" && s.watch_date && (
                  <p style={{ fontSize: 10, color: "#ef4444", margin: "4px 0 0" }}>
                    Watch date: {s.watch_date}
                  </p>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Collapsible Sections */}
      {sections.map((section, idx) => {
        const title = section.split("\n")[0]?.trim() || `Section ${idx + 1}`;
        const body = section.split("\n").slice(1).join("\n");
        const isExpanded = expandedSections[idx] !== false;

        return (
          <div
            key={idx}
            style={{
              background: "#14141a",
              border: "1px solid #27272a",
              borderRadius: 12,
              marginBottom: 8,
              overflow: "hidden",
            }}
          >
            <button
              onClick={() => toggleSection(idx)}
              style={{
                width: "100%",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                padding: "12px 16px",
                background: "transparent",
                border: "none",
                color: "#e4e4e7",
                fontSize: 13,
                fontWeight: 600,
                cursor: "pointer",
                textAlign: "left",
              }}
            >
              <span>{title}</span>
              <span style={{ color: "#71717a", fontSize: 16 }}>
                {isExpanded ? "▲" : "▼"}
              </span>
            </button>
            {isExpanded && (
              <div
                style={{
                  padding: "0 16px 12px",
                  fontSize: 13,
                  lineHeight: 1.6,
                  color: "#a1a1aa",
                }}
              >
                <SafeMarkdown content={body} className="report-markdown" />
              </div>
            )}
          </div>
        );
      })}

      {/* Action Items Checklist */}
      {actionItems.length > 0 && (
        <div
          style={{
            background: "#14141a",
            border: "1px solid #27272a",
            borderRadius: 12,
            padding: 16,
            marginTop: 12,
          }}
        >
          <h3 style={{ margin: "0 0 8px", fontSize: 14, color: "#00e676" }}>
            Risk Recommendations
          </h3>
          {actionItems.map((item, idx) => (
            <label
              key={idx}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "4px 0",
                cursor: "pointer",
                fontSize: 13,
                color: checkedItems[idx] ? "#71717a" : "#e4e4e7",
                textDecoration: checkedItems[idx] ? "line-through" : "none",
              }}
            >
              <input
                type="checkbox"
                checked={checkedItems[idx] || false}
                onChange={() =>
                  setCheckedItems((prev) => ({ ...prev, [idx]: !prev[idx] }))
                }
                style={{ accentColor: "#00e676" }}
              />
              {item}
            </label>
          ))}
        </div>
      )}

      <style jsx>{`
        .report-markdown strong { color: #e4e4e7; }
        .report-markdown table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 12px; }
        .report-markdown td { padding: 6px 10px; border: 1px solid #27272a; }
        .report-markdown hr { border: none; border-top: 1px solid #27272a; margin: 12px 0; }
        .report-markdown ul { padding-left: 20px; margin: 4px 0; }
        .report-markdown li { margin: 2px 0; }
      `}</style>
    </div>
  );
}


