import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def markdown_to_html(markdown_text: str) -> str:
    lines = markdown_text.split("\n")
    html_parts = []
    in_table = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("# "):
            html_parts.append(f"<h1>{stripped[2:]}</h1>")
        elif stripped.startswith("## "):
            html_parts.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("### "):
            html_parts.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("|"):
            cells = [c.strip() for c in stripped.split("|")[1:-1]]
            if not in_table:
                html_parts.append("<table>")
                in_table = True
            if all(c == "---" or c == ":" for c in cells):
                continue
            html_parts.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
        else:
            if in_table:
                html_parts.append("</table>")
                in_table = False
            if stripped.startswith("- "):
                html_parts.append(f"<li>{stripped[2:]}</li>")
            elif stripped == "---":
                html_parts.append("<hr/>")
            elif stripped == "":
                html_parts.append("<br/>")
            else:
                html_parts.append(f"<p>{stripped}</p>")

    if in_table:
        html_parts.append("</table>")

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  @page {{
    size: A4;
    margin: 2cm 1.5cm;
    @bottom-center {{
      content: "Page " counter(page) " of " counter(pages);
      font-size: 9px;
      color: #666;
      font-family: 'Helvetica Neue', Arial, sans-serif;
    }}
  }}
  body {{
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 11px;
    line-height: 1.6;
    color: #1a1a2e;
    margin: 0;
    padding: 0;
  }}
  .header {{
    background: linear-gradient(135deg, #0a1628 0%, #1a1a3e 100%);
    color: #fff;
    padding: 30px 30px 20px 30px;
    margin: -20px -20px 20px -20px;
    border-radius: 0 0 8px 8px;
  }}
  .header h1 {{
    margin: 0;
    font-size: 22px;
    color: #22c55e;
  }}
  .header .subtitle {{
    font-size: 11px;
    color: #94a3b8;
    margin-top: 4px;
  }}
  h1 {{ color: #1a1a2e; font-size: 20px; border-bottom: 2px solid #22c55e; padding-bottom: 6px; }}
  h2 {{ color: #1a1a2e; font-size: 15px; margin-top: 20px; }}
  h3 {{ color: #334155; font-size: 13px; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 10px; }}
  td {{ padding: 6px 10px; border: 1px solid #e2e8f0; text-align: left; }}
  tr:nth-child(even) {{ background: #f8fafc; }}
  tr:nth-child(odd) {{ background: #fff; }}
  li {{ margin: 4px 0; }}
  hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 15px 0; }}
  p {{ margin: 6px 0; text-align: justify; }}
  .footer {{
    margin-top: 30px;
    padding-top: 10px;
    border-top: 1px solid #e2e8f0;
    font-size: 8px;
    color: #94a3b8;
  }}
  .health-badge {{
    display: inline-block;
    padding: 3px 10px;
    border-radius: 12px;
    font-weight: bold;
    font-size: 12px;
  }}
  .health-good {{ background: #22c55e20; color: #16a34a; }}
  .health-warn {{ background: #f59e0b20; color: #d97706; }}
  .health-bad {{ background: #ef444420; color: #dc2626; }}
</style>
</head>
<body>
<div class="header">
  <h1>LiveRisk</h1>
  <div class="subtitle">Portfolio Intelligence Report — Vera AI</div>
</div>
{''.join(html_parts)}
<div class="footer">
  Generated by Vera AI on {datetime.now().strftime("%Y-%m-%d %H:%M")} · Confidential
</div>
</body>
</html>"""
    return html


def generate_pdf(report_markdown: str, user_id: str) -> bytes:
    try:
        from weasyprint import HTML
        html = markdown_to_html(report_markdown)
        pdf_bytes = HTML(string=html).write_pdf()
        logger.info(f"PDF generated for user {user_id}: {len(pdf_bytes)} bytes")
        return pdf_bytes
    except ImportError:
        logger.error("weasyprint not installed — cannot generate PDF")
        raise
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise
